### 00 - Text - Preprocessing - Pitt

In this notebook, we will pre-process text files in Pitt set and split them into train / dev / test set with text.

In [1]:
import pandas as pd

In [2]:
fname_train = "../data/pitt/pitt_train.csv"
fname_dev = "../data/pitt/pitt_dev.csv"
fname_test = "../data/pitt/pitt_test.csv"
fname_pitt_text = "../data/pitt/pitt.csv"

In [3]:
train_df = pd.read_csv(fname_train)
dev_df = pd.read_csv(fname_dev)
test_df = pd.read_csv(fname_test)
text_df = pd.read_csv(fname_pitt_text)

In [4]:
# quick look at the dataframes
print("Train len =", len(train_df))
train_df['id'] = train_df['id'].astype(str)
train_df.head()

Train len = 174

    id target  age_of_first_test     sex  less_than_65
0  714     ad                 79    male         False
1  466     ad                 78  female         False
2  511     ad                 75  female         False
3  609     ad                 70  female         False
4  504     ad                 78    male         False

In [5]:
print("Dev len =", len(dev_df))
dev_df['id'] = dev_df['id'].astype(str)
dev_df.head()

Dev len = 59

    id target  age_of_first_test     sex  less_than_65
0  234     ad                 66    male         False
1  256     cn                 67    male         False
2  497     ad                 70  female         False
3  264     ad                 65  female         False
4  297     cn                 64    male          True

In [6]:
print("Test len =", len(test_df))
test_df['id'] = test_df['id'].astype(str)
test_df.head()

Test len = 59

    id target  age_of_first_test     sex  less_than_65
0  358     ad                 60  female          True
1   34     cn                 70    male         False
2   42     cn                 56  female          True
3  650     ad                 87  female         False
4  332     cn                 50    male          True

In [7]:
print("Pitt text len =", len(text_df))
text_df.drop(text_df.columns[0], axis=1, inplace=True)
text_df.head()

Pitt text len = 549

   id       file target                                               text
0   1  001-0.cha     AD  mhm .\nalright .\nthere's &-um a young boy tha...
1   1  001-2.cha     AD  mhm .\nthere's a young boy &-uh going in a coo...
2   3  003-0.cha     AD  here's a cookie jar .\nand the lid is off the ...
3   5  005-0.cha     AD  the boy is slipping off the stool .\nhe's tryi...
4   5  005-2.cha     AD  okay ‡ he's fallin(g) off a chair  .\nshe's &-...

In [8]:
def get_split_name(id):
    """
        return split name (train/dev/set) given id
    """
    result = "train" # default
    id = str(id)
    if len(dev_df.query("id == @id")) > 0:
        result = "dev"
    elif len(test_df.query("id == @id")) > 0:
        result = "test"
        
    return result

assert get_split_name("714") == "train"
assert get_split_name("466") == "train"
assert get_split_name("511") == "train"

assert get_split_name("234") == "dev"
assert get_split_name("256") == "dev"
assert get_split_name("497") == "dev"


assert get_split_name("358") == "test"
assert get_split_name("34") == "test"
assert get_split_name("332") == "test"

print("Passed")

Passed

In [9]:
# apply to text df
text_df["split_name"] = text_df["id"].apply(lambda id: get_split_name(id))
text_df.head()

,id,file,target,text,split_name
0,1,001-0.cha,AD,mhm .\nalright .\nthere's &-um a young boy tha...,test
1,1,001-2.cha,AD,mhm .\nthere's a young boy &-uh going in a coo...,test
2,3,003-0.cha,AD,here's a cookie jar .\nand the lid is off the ...,train
3,5,005-0.cha,AD,the boy is slipping off the stool .\nhe's tryi...,train
4,5,005-2.cha,AD,okay ‡ he's fallin(g) off a chair .\nshe's &-...,train

In [10]:
assert text_df.query("id == 609")["split_name"].iloc[0] == "train"
assert text_df.query("id == 504")["split_name"].iloc[0] == "train"

assert text_df.query("id == 264")["split_name"].iloc[0] == "dev"
assert text_df.query("id == 297")["split_name"].iloc[0] == "dev"

assert text_df.query("id == 650")["split_name"].iloc[0] == "test"
assert text_df.query("id == 332")["split_name"].iloc[0] == "test"
print("Passed")

Passed

In [11]:
# split to 3 files
train_fname_out = "../data/pitt/pitt_train_txt.csv"
dev_fname_out = "../data/pitt/pitt_dev_txt.csv"
test_fname_out = "../data/pitt/pitt_test_txt.csv"

txt_train_df = text_df.query("split_name == 'train'")
txt_dev_df = text_df.query("split_name == 'dev'")
txt_test_df = text_df.query("split_name == 'test'")

In [12]:
txt_train_df.head()

,id,file,target,text,split_name
2,3,003-0.cha,AD,here's a cookie jar .\nand the lid is off the ...,train
3,5,005-0.cha,AD,the boy is slipping off the stool .\nhe's tryi...,train
4,5,005-2.cha,AD,okay ‡ he's fallin(g) off a chair .\nshe's &-...,train
5,7,007-1.cha,AD,xxx .\ncan I look at it and tell you ?\noh oka...,train
6,7,007-3.cha,AD,well the girl is telling the boy to get the co...,train

In [13]:
txt_dev_df.head()

,id,file,target,text,split_name
13,16,016-0.cha,AD,guy or a boy reaching for a cookie jar &-uh ti...,dev
14,16,016-1.cha,AD,uh the water's spilling over .\ndrying the dis...,dev
15,16,016-3.cha,AD,a boy is reaching for the cookie jar and tripp...,dev
16,16,016-4.cha,AD,well the little girl wants the cookie that the...,dev
26,33,033-0.cha,AD,okay .\napparently a mother and a daughter and...,dev

In [14]:
txt_test_df.head()

,id,file,target,text,split_name
0,1,001-0.cha,AD,mhm .\nalright .\nthere's &-um a young boy tha...,test
1,1,001-2.cha,AD,mhm .\nthere's a young boy &-uh going in a coo...,test
18,23,023-0.cha,AD,(..) well I see the mother .\nwhat's she doin(...,test
19,23,023-2.cha,AD,well you see <the little> the little boy stea...,test
33,39,039-0.cha,AD,okay we see &-um first of all &-uh the sink is...,test

In [15]:
# write to csv files
print("Writing to csv files...")
txt_train_df.to_csv(train_fname_out,
                    index=False
                   )
txt_dev_df.to_csv(dev_fname_out,
                  index=False
                 )
txt_test_df.to_csv(test_fname_out,
                   index=False
                   )

print("Completed")

Writing to csv files...
Completed