## 01 - Pitt - Preprocessing

We have new Pitt dataset from DementiaBank. We will extract the transcribed text and export to a csv file

In [1]:
# import required packages
import pandas as pd
import os
import re

In [2]:
# labels
# AD = Alzheimer's Disease (positive class)
# CN = Cognitively Normal (negative class)

In [3]:
# please point to correct downloaded transcribed folders of the original dataset
data_path = "../../../data/" 
path_ad = data_path + "TalkBank downloads/Pitt/Dementia/Cookie/"
path_cn = data_path + "TalkBank downloads/Pitt/Control/Cookie/"

In [4]:
data = {"ad":[], 
        "cn":[]
       }

file_names = {"ad":[],
              "cn":[]
             }

In [5]:
def line_clean(line):
    """
        Clean line from extra information like "*PAR: ", "\x1530_5640\x15", etc
    """
    result = line
    if result.startswith("*PAR"):
        result = result.replace("*PAR:\t", "")
        result = re.sub(".*", "", result)
        result = re.sub("\[.*\]", "", result)
        result = result.strip("&-+<").strip()
    else:
        result = ""
    return result

s = '*PAR:\tthe scene is <in the> [/] in the kitchen . \x1530_5640\x15\n'
assert line_clean(s) == "the scene is <in the>  in the kitchen ."

In [6]:
def read_data(path):
    """
        get data from "txt" files from a specified folder (ad/cn)
        returns list of text (strings)
    """
    result = []
    filenames = []

    # get only txt files
    files = [item
             for item in os.listdir(path)
             if item.endswith("cha")
            ]
    
    for fname in files:
        print("Processing files =", fname) #, end="\r")
        with open(path + fname, encoding="utf-8") as f:
            lines = f.readlines()
            print("Line counts =", len(lines)) #, end="\r")
            # apply filter to clean text
            lines = [line_clean(line)
                     for line in lines
                     if line.startswith("*PAR")
                    ]
            print("After cleaning, Line counts =", len(lines)) #, end="\r")

            text = "\n".join(lines)
            result.append(text)
            filenames.append(fname.replace(".cha", "")) # remove file extensions

    return (result, filenames)

In [7]:
data["ad"], file_names["ad"] = read_data(path_ad)
data["cn"], file_names["cn"] = read_data(path_cn)

Processing files = 001-0.cha
Line counts = 85
After cleaning, Line counts = 10
Processing files = 001-2.cha
Line counts = 125
After cleaning, Line counts = 13
Processing files = 003-0.cha
Line counts = 172
After cleaning, Line counts = 23
Processing files = 005-0.cha
Line counts = 73
After cleaning, Line counts = 9
Processing files = 005-2.cha
Line counts = 92
After cleaning, Line counts = 7
Processing files = 007-1.cha
Line counts = 105
After cleaning, Line counts = 13
Processing files = 007-3.cha
Line counts = 85
After cleaning, Line counts = 9
Processing files = 010-0.cha
Line counts = 186
After cleaning, Line counts = 22
Processing files = 010-1.cha
Line counts = 201
After cleaning, Line counts = 27
Processing files = 010-2.cha
Line counts = 208
After cleaning, Line counts = 32
Processing files = 010-3.cha
Line counts = 128
After cleaning, Line counts = 17
Processing files = 010-4.cha
Line counts = 92
After cleaning, Line counts = 9
Processing files = 014-2.cha
Line counts = 161
After cleaning, Line counts = 17
Processing files = 016-0.cha
Line counts = 65
After cleaning, Line counts = 6
Processing files = 016-1.cha
Line counts = 57
After cleaning, Line counts = 8
Processing files = 016-3.cha
Line counts = 62
After cleaning, Line counts = 5
Processing files = 016-4.cha
Line counts = 108
After cleaning, Line counts = 13
Processing files = 018-0.cha
Line counts = 199
After cleaning, Line counts = 21
Processing files = 023-0.cha
Line counts = 91
After cleaning, Line counts = 10
Processing files = 023-2.cha
Line counts = 129
After cleaning, Line counts = 14
Processing files = 024-1.cha
Line counts = 68
After cleaning, Line counts = 8
Processing files = 024-2.cha
Line counts = 91
After cleaning, Line counts = 12
Processing files = 029-0.cha
Line counts = 114
After cleaning, Line counts = 15
Processing files = 029-1.cha
Line counts = 215
After cleaning, Line counts = 27
Processing files = 030-0.cha
Line counts = 148
After cleaning, Line counts = 19
Processing files = 030-1.cha
Line counts = 125
After cleaning, Line counts = 12
Processing files = 033-0.cha
Line counts = 87
After cleaning, Line counts = 7
Processing files = 033-1.cha
Line counts = 124
After cleaning, Line counts = 13
Processing files = 033-2.cha
Line counts = 95
After cleaning, Line counts = 14
Processing files = 033-3.cha
Line counts = 82
After cleaning, Line counts = 9
Processing files = 033-4.cha
Line counts = 118
After cleaning, Line counts = 10
Processing files = 035-0.cha
Line counts = 90
After cleaning, Line counts = 11
Processing files = 035-1.cha
Line counts = 90
After cleaning, Line counts = 13
Processing files = 039-0.cha
Line counts = 81
After cleaning, Line counts = 9
Processing files = 043-0.cha
Line counts = 103
After cleaning, Line counts = 13
Processing files = 046-0.cha
Line counts = 113
After cleaning, Line counts = 16
Processing files = 046-2.cha
Line counts = 134
After cleaning, Line counts = 14
Processing files = 049-0.cha
Line counts = 153
After cleaning, Line counts = 17
Processing files = 049-1.cha
Line counts = 113
After cleaning, Line counts = 15
Processing files = 050-0.cha
Line counts = 88
After cleaning, Line counts = 12
Processing files = 051-0.cha
Line counts = 103
After cleaning, Line counts = 14
Processing files = 051-1.cha
Line counts = 90
After cleaning, Line counts = 12
Processing files = 051-2.cha
Line counts = 207
After cleaning, Line counts = 27
Processing files = 051-3.cha
Line counts = 151
After cleaning, Line counts = 24
Processing files = 053-1.cha
Line counts = 238
After cleaning, Line counts = 25
Processing files = 057-0.cha
Line counts = 91
After cleaning, Line counts = 12
Processing files = 057-1.cha
Line counts = 96
After cleaning, Line counts = 15
Processing files = 057-2.cha
Line counts = 149
After cleaning, Line counts = 24
Processing files = 058-0.cha
Line counts = 77
After cleaning, Line counts = 8
Processing files = 058-1.cha
Line counts = 119
After cleaning, Line counts = 15
Processing files = 058-3.cha
Line counts = 52
After cleaning, Line counts = 5
Processing files = 058-4.cha
Line counts = 75
After cleaning, Line counts = 5
Processing files = 061-0.cha
Line counts = 165
After cleaning, Line counts = 17
Processing files = 061-1.cha
Line counts = 82
After cleaning, Line counts = 11
Processing files = 062-0.cha
Line counts = 72
After cleaning, Line counts = 8
Processing files = 065-0.cha
Line counts = 100
After cleaning, Line counts = 12
Processing files = 065-1.cha
Line counts = 115
After cleaning, Line counts = 14
Processing files = 065-2.cha
Line counts = 164
After cleaning, Line counts = 22
Processing files = 066-0.cha
Line counts = 113
After cleaning, Line counts = 12
Processing files = 067-1.cha
Line counts = 103
After cleaning, Line counts = 11
Processing files = 067-2.cha
Line counts = 130
After cleaning, Line counts = 15
Processing files = 070-2.cha
Line counts = 68
After cleaning, Line counts = 9
Processing files = 076-0.cha
Line counts = 172
After cleaning, Line counts = 18
Processing files = 076-2.cha
Line counts = 235
After cleaning, Line counts = 28
Processing files = 076-4.cha
Line counts = 101
After cleaning, Line counts = 11
Processing files = 078-0.cha
Line counts = 127
After cleaning, Line counts = 16
Processing files = 078-1.cha
Line counts = 132
After cleaning, Line counts = 17
Processing files = 087-1.cha
Line counts = 105
After cleaning, Line counts = 12
Processing files = 089-0.cha
Line counts = 136
After cleaning, Line counts = 18
Processing files = 091-0.cha
Line counts = 89
After cleaning, Line counts = 8
Processing files = 091-1.cha
Line counts = 106
After cleaning, Line counts = 9
Processing files = 091-2.cha
Line counts = 73
After cleaning, Line counts = 7
Processing files = 094-1.cha
Line counts = 130
After cleaning, Line counts = 16
Processing files = 094-2.cha
Line counts = 147
After cleaning, Line counts = 14
Processing files = 094-3.cha
Line counts = 102
After cleaning, Line counts = 14
Processing files = 097-1.cha
Line counts = 77
After cleaning, Line counts = 7
Processing files = 120-0.cha
Line counts = 80
After cleaning, Line counts = 9
Processing files = 120-1.cha
Line counts = 122
After cleaning, Line counts = 13
Processing files = 120-2.cha
Line counts = 82
After cleaning, Line counts = 11
Processing files = 120-3.cha
Line counts = 112
After cleaning, Line counts = 12
Processing files = 120-4.cha
Line counts = 88
After cleaning, Line counts = 8
Processing files = 122-0.cha
Line counts = 88
After cleaning, Line counts = 8
Processing files = 122-1.cha
Line counts = 109
After cleaning, Line counts = 10
Processing files = 125-0.cha
Line counts = 116
After cleaning, Line counts = 12
Processing files = 127-0.cha
Line counts = 68
After cleaning, Line counts = 7
Processing files = 134-0.cha
Line counts = 87
After cleaning, Line counts = 10
Processing files = 134-1.cha
Line counts = 55
After cleaning, Line counts = 5
Processing files = 134-2.cha
Line counts = 72
After cleaning, Line counts = 6
Processing files = 134-3.cha
Line counts = 96
After cleaning, Line counts = 9
Processing files = 144-0.cha
Line counts = 129
After cleaning, Line counts = 13
Processing files = 144-1.cha
Line counts = 117
After cleaning, Line counts = 12
Processing files = 148-0.cha
Line counts = 70
After cleaning, Line counts = 9
Processing files = 154-0.cha
Line counts = 109
After cleaning, Line counts = 12
Processing files = 154-1.cha
Line counts = 84
After cleaning, Line counts = 5
Processing files = 157-0.cha
Line counts = 124
After cleaning, Line counts = 14
Processing files = 157-1.cha
Line counts = 276
After cleaning, Line counts = 33
Processing files = 157-2.cha
Line counts = 92
After cleaning, Line counts = 10
Processing files = 164-1.cha
Line counts = 60
After cleaning, Line counts = 8
Processing files = 164-2.cha
Line counts = 46
After cleaning, Line counts = 6
Processing files = 164-3.cha
Line counts = 68
After cleaning, Line counts = 8
Processing files = 168-0.cha
Line counts = 32
After cleaning, Line counts = 2
Processing files = 168-1.cha
Line counts = 113
After cleaning, Line counts = 14
Processing files = 172-1.cha
Line counts = 85
After cleaning, Line counts = 10
Processing files = 172-2.cha
Line counts = 52
After cleaning, Line counts = 4
Processing files = 172-3.cha
Line counts = 80
After cleaning, Line counts = 11
Processing files = 173-1.cha
Line counts = 120
After cleaning, Line counts = 8
Processing files = 178-0.cha
Line counts = 67
After cleaning, Line counts = 6
Processing files = 178-1.cha
Line counts = 93
After cleaning, Line counts = 12
Processing files = 181-0.cha
Line counts = 73
After cleaning, Line counts = 9
Processing files = 181-1.cha
Line counts = 146
After cleaning, Line counts = 14
Processing files = 181-2.cha
Line counts = 68
After cleaning, Line counts = 7
Processing files = 181-3.cha
Line counts = 131
After cleaning, Line counts = 14
Processing files = 183-0.cha
Line counts = 60
After cleaning, Line counts = 7
Processing files = 183-1.cha
Line counts = 77
After cleaning, Line counts = 9
Processing files = 183-2.cha
Line counts = 84
After cleaning, Line counts = 7
Processing files = 183-3.cha
Line counts = 78
After cleaning, Line counts = 9
Processing files = 184-0.cha
Line counts = 83
After cleaning, Line counts = 10
Processing files = 184-1.cha
Line counts = 148
After cleaning, Line counts = 16
Processing files = 184-2.cha
Line counts = 97
After cleaning, Line counts = 6
Processing files = 203-0.cha
Line counts = 132
After cleaning, Line counts = 15
Processing files = 203-1.cha
Line counts = 93
After cleaning, Line counts = 10
Processing files = 205-1.cha
Line counts = 170
After cleaning, Line counts = 22
Processing files = 206-0.cha
Line counts = 182
After cleaning, Line counts = 26
Processing files = 207-0.cha
Line counts = 508
After cleaning, Line counts = 65
Processing files = 212-0.cha
Line counts = 134
After cleaning, Line counts = 19
Processing files = 212-1.cha
Line counts = 85
After cleaning, Line counts = 12
Processing files = 212-2.cha
Line counts = 161
After cleaning, Line counts = 21
Processing files = 212-3.cha
Line counts = 129
After cleaning, Line counts = 19
Processing files = 213-1.cha
Line counts = 162
After cleaning, Line counts = 18
Processing files = 213-2.cha
Line counts = 151
After cleaning, Line counts = 19
Processing files = 213-3.cha
Line counts = 136
After cleaning, Line counts = 12
Processing files = 216-0.cha
Line counts = 65
After cleaning, Line counts = 9
Processing files = 216-1.cha
Line counts = 111
After cleaning, Line counts = 12
Processing files = 218-0.cha
Line counts = 159
After cleaning, Line counts = 17
Processing files = 218-1.cha
Line counts = 226
After cleaning, Line counts = 20
Processing files = 220-0.cha
Line counts = 118
After cleaning, Line counts = 16
Processing files = 220-1.cha
Line counts = 88
After cleaning, Line counts = 8
Processing files = 221-0.cha
Line counts = 178
After cleaning, Line counts = 24
Processing files = 221-1.cha
Line counts = 100
After cleaning, Line counts = 10
Processing files = 221-2.cha
Line counts = 104
After cleaning, Line counts = 12
Processing files = 221-3.cha
Line counts = 91
After cleaning, Line counts = 11
Processing files = 222-0.cha
Line counts = 126
After cleaning, Line counts = 10
Processing files = 222-1.cha
Line counts = 142
After cleaning, Line counts = 15
Processing files = 223-0.cha
Line counts = 145
After cleaning, Line counts = 19
Processing files = 223-1.cha
Line counts = 91
After cleaning, Line counts = 10
Processing files = 226-0.cha
Line counts = 120
After cleaning, Line counts = 17
Processing files = 234-0.cha
Line counts = 86
After cleaning, Line counts = 9
Processing files = 235-0.cha
Line counts = 175
After cleaning, Line counts = 19
Processing files = 235-2.cha
Line counts = 104
After cleaning, Line counts = 13
Processing files = 236-0.cha
Line counts = 126
After cleaning, Line counts = 12
Processing files = 237-1.cha
Line counts = 103
After cleaning, Line counts = 10
Processing files = 237-2.cha
Line counts = 131
After cleaning, Line counts = 18
Processing files = 238-0.cha
Line counts = 131
After cleaning, Line counts = 16
Processing files = 244-0.cha
Line counts = 170
After cleaning, Line counts = 25
Processing files = 247-0.cha
Line counts = 177
After cleaning, Line counts = 16
Processing files = 252-0.cha
Line counts = 68
After cleaning, Line counts = 7
Processing files = 252-1.cha
Line counts = 84
After cleaning, Line counts = 10
Processing files = 252-2.cha
Line counts = 77
After cleaning, Line counts = 4
Processing files = 257-0.cha
Line counts = 162
After cleaning, Line counts = 23
Processing files = 257-2.cha
Line counts = 184
After cleaning, Line counts = 25
Processing files = 260-1.cha
Line counts = 78
After cleaning, Line counts = 8
Processing files = 260-2.cha
Line counts = 85
After cleaning, Line counts = 8
Processing files = 264-0.cha
Line counts = 137
After cleaning, Line counts = 17
Processing files = 268-0.cha
Line counts = 255
After cleaning, Line counts = 27
Processing files = 269-0.cha
Line counts = 149
After cleaning, Line counts = 17
Processing files = 269-1.cha
Line counts = 132
After cleaning, Line counts = 14
Processing files = 270-0.cha
Line counts = 148
After cleaning, Line counts = 18
Processing files = 270-1.cha
Line counts = 84
After cleaning, Line counts = 11
Processing files = 270-2.cha
Line counts = 108
After cleaning, Line counts = 14
Processing files = 271-2.cha
Line counts = 54
After cleaning, Line counts = 4
Processing files = 276-0.cha
Line counts = 233
After cleaning, Line counts = 30
Processing files = 279-0.cha
Line counts = 171
After cleaning, Line counts = 25
Processing files = 279-1.cha
Line counts = 67
After cleaning, Line counts = 10
Processing files = 282-0.cha
Line counts = 99
After cleaning, Line counts = 12
Processing files = 282-1.cha
Line counts = 88
After cleaning, Line counts = 13
Processing files = 282-2.cha
Line counts = 111
After cleaning, Line counts = 12
Processing files = 283-0.cha
Line counts = 141
After cleaning, Line counts = 21
Processing files = 283-1.cha
Line counts = 99
After cleaning, Line counts = 13
Processing files = 289-2.cha
Line counts = 72
After cleaning, Line counts = 9
Processing files = 291-1.cha
Line counts = 71
After cleaning, Line counts = 7
Processing files = 291-2.cha
Line counts = 74
After cleaning, Line counts = 8
Processing files = 293-1.cha
Line counts = 100
After cleaning, Line counts = 14
Processing files = 306-0.cha
Line counts = 117
After cleaning, Line counts = 17
Processing files = 310-0.cha
Line counts = 98
After cleaning, Line counts = 13
Processing files = 311-0.cha
Line counts = 71
After cleaning, Line counts = 7
Processing files = 319-0.cha
Line counts = 183
After cleaning, Line counts = 18
Processing files = 325-0.cha
Line counts = 92
After cleaning, Line counts = 8
Processing files = 325-1.cha
Line counts = 77
After cleaning, Line counts = 7
Processing files = 329-0.cha
Line counts = 196
After cleaning, Line counts = 27
Processing files = 334-0.cha
Line counts = 212
After cleaning, Line counts = 32
Processing files = 334-1.cha
Line counts = 152
After cleaning, Line counts = 17
Processing files = 337-0.cha
Line counts = 96
After cleaning, Line counts = 13
Processing files = 338-0.cha
Line counts = 42
After cleaning, Line counts = 6
Processing files = 339-0.cha
Line counts = 79
After cleaning, Line counts = 12
Processing files = 341-0.cha
Line counts = 91
After cleaning, Line counts = 10
Processing files = 342-0.cha
Line counts = 102
After cleaning, Line counts = 16
Processing files = 342-1.cha
Line counts = 107
After cleaning, Line counts = 15
Processing files = 343-0.cha
Line counts = 110
After cleaning, Line counts = 14
Processing files = 344-0.cha
Line counts = 87
After cleaning, Line counts = 9
Processing files = 344-2.cha
Line counts = 149
After cleaning, Line counts = 14
Processing files = 346-0.cha
Line counts = 108
After cleaning, Line counts = 15
Processing files = 349-0.cha
Line counts = 94
After cleaning, Line counts = 12
Processing files = 349-1.cha
Line counts = 116
After cleaning, Line counts = 17
Processing files = 350-0.cha
Line counts = 185
After cleaning, Line counts = 24
Processing files = 350-1.cha
Line counts = 214
After cleaning, Line counts = 27
Processing files = 354-0.cha
Line counts = 104
After cleaning, Line counts = 14
Processing files = 355-0.cha
Line counts = 94
After cleaning, Line counts = 12
Processing files = 355-1.cha
Line counts = 122
After cleaning, Line counts = 16
Processing files = 356-0.cha
Line counts = 159
After cleaning, Line counts = 13
Processing files = 356-1.cha
Line counts = 97
After cleaning, Line counts = 12
Processing files = 357-0.cha
Line counts = 98
After cleaning, Line counts = 16
Processing files = 358-0.cha
Line counts = 72
After cleaning, Line counts = 10
Processing files = 358-1.cha
Line counts = 112
After cleaning, Line counts = 15
Processing files = 360-0.cha
Line counts = 83
After cleaning, Line counts = 12
Processing files = 361-0.cha
Line counts = 90
After cleaning, Line counts = 11
Processing files = 362-0.cha
Line counts = 126
After cleaning, Line counts = 13
Processing files = 362-1.cha
Line counts = 78
After cleaning, Line counts = 8
Processing files = 368-0.cha
Line counts = 80
After cleaning, Line counts = 11
Processing files = 369-0.cha
Line counts = 93
After cleaning, Line counts = 9
Processing files = 381-0.cha
Line counts = 70
After cleaning, Line counts = 11
Processing files = 381-1.cha
Line counts = 83
After cleaning, Line counts = 9
Processing files = 450-0.cha
Line counts = 99
After cleaning, Line counts = 13
Processing files = 450-1.cha
Line counts = 93
After cleaning, Line counts = 9
Processing files = 458-0.cha
Line counts = 91
After cleaning, Line counts = 12
Processing files = 461-0.cha
Line counts = 127
After cleaning, Line counts = 19
Processing files = 465-0.cha
Line counts = 61
After cleaning, Line counts = 8
Processing files = 466-0.cha
Line counts = 73
After cleaning, Line counts = 11
Processing files = 466-1.cha
Line counts = 76
After cleaning, Line counts = 6
Processing files = 468-0.cha
Line counts = 76
After cleaning, Line counts = 11
Processing files = 470-1.cha
Line counts = 190
After cleaning, Line counts = 22
Processing files = 471-0.cha
Line counts = 34
After cleaning, Line counts = 5
Processing files = 472-0.cha
Line counts = 74
After cleaning, Line counts = 7
Processing files = 474-0.cha
Line counts = 86
After cleaning, Line counts = 7
Processing files = 476-0.cha
Line counts = 140
After cleaning, Line counts = 20
Processing files = 488-0.cha
Line counts = 87
After cleaning, Line counts = 7
Processing files = 488-1.cha
Line counts = 71
After cleaning, Line counts = 5
Processing files = 492-0.cha
Line counts = 139
After cleaning, Line counts = 13
Processing files = 493-0.cha
Line counts = 150
After cleaning, Line counts = 20
Processing files = 493-1.cha
Line counts = 128
After cleaning, Line counts = 18
Processing files = 497-0.cha
Line counts = 106
After cleaning, Line counts = 14
Processing files = 497-1.cha
Line counts = 122
After cleaning, Line counts = 13
Processing files = 504-0.cha
Line counts = 100
After cleaning, Line counts = 11
Processing files = 506-0.cha
Line counts = 90
After cleaning, Line counts = 10
Processing files = 508-0.cha
Line counts = 136
After cleaning, Line counts = 17
Processing files = 508-1.cha
Line counts = 122
After cleaning, Line counts = 17
Processing files = 511-0.cha
Line counts = 118
After cleaning, Line counts = 11
Processing files = 515-1.cha
Line counts = 96
After cleaning, Line counts = 10
Processing files = 526-1.cha
Line counts = 139
After cleaning, Line counts = 14
Processing files = 527-0.cha
Line counts = 89
After cleaning, Line counts = 11
Processing files = 527-1.cha
Line counts = 78
After cleaning, Line counts = 7
Processing files = 528-0.cha
Line counts = 96
After cleaning, Line counts = 9
Processing files = 529-0.cha
Line counts = 78
After cleaning, Line counts = 7
Processing files = 530-0.cha

In [8]:
# double check data
assert len(data["ad"]) == 306
assert len(data["cn"]) == 243
assert data["ad"][0].startswith("mhm")
assert data["ad"][1].startswith("mhm")
assert data["cn"][0].startswith("the scene is <in the>")
assert data["cn"][1].startswith("oh I see the sink is running over")
print("Passed")

Passed

In [9]:
# assert filenames
assert file_names["ad"][0].startswith("001-0")
assert file_names["ad"][1].startswith("001-2")
assert file_names["ad"][-1].startswith("714-0")

assert file_names["cn"][0].startswith("002-0")
assert file_names["cn"][1].startswith("002-1")
assert file_names["cn"][-1].startswith("709-2")

print("Passed")

Passed

In [10]:
# take a look at the data
print(data["ad"][0][:100])

mhm .
alright .
there's &-um a young boy that's getting a cookie jar .
and it  he's &-uh in bad shap

In [11]:
# take a look at the data
print(data["cn"][0][:100])

the scene is <in the>  in the kitchen .
the mother is wiping dishes and the water is running on the

In [12]:
print(file_names["ad"][0:5])

['001-0', '001-2', '003-0', '005-0', '005-2']

In [13]:
print(file_names["cn"][0:5])

['002-0', '002-1', '002-2', '002-3', '006-2']

In [14]:
# combine data into a dataframe, for export to a csv for further processing
data_dict = {
    "file_id": [],  #  file name
    "text": [],    # the transcript
    "target": []   # the target: positive (AD), negative (CN)
}
for item, fname in zip(data["ad"], file_names["ad"]):
    data_dict["file_id"].append(fname)
    data_dict["text"].append(item)
    data_dict["target"].append("AD")

for item, fname in zip(data["cn"], file_names["cn"]):
    data_dict["file_id"].append(fname)
    data_dict["text"].append(item)
    data_dict["target"].append("CN")

print("Text count =", len(data_dict["text"]))
print("Target count =", len(data_dict["target"]))
print("File_id count =", len(data_dict["target"]))

Text count = 549
Target count = 549
File_id count = 549

In [15]:
# create a dataframe to export to csv
data_df = pd.DataFrame(data_dict)
print(len(data_df))
data_df.head()

549

  file_id                                               text target
0   001-0  mhm .\nalright .\nthere's &-um a young boy tha...     AD
1   001-2  mhm .\nthere's a young boy &-uh going in a coo...     AD
2   003-0  here's a cookie jar .\nand the lid is off the ...     AD
3   005-0  the boy is slipping off the stool .\nhe's tryi...     AD
4   005-2  okay ‡ he's fallin(g) off a chair  .\nshe's &-...     AD

In [16]:
data_df.describe()

       file_id                                               text target
count      549                                                549    549
unique     549                                                549      2
top      001-0  mhm .\nalright .\nthere's &-um a young boy tha...     AD
freq         1                                                  1    306

We can see we have total of 549 examples, with 306 (about 55%) positive (AD) and 243 (about 45%) negative (CN). The dataset is relatively balanced, although there are slightly more examples with positive labels.

### Create CSV output

In [17]:
# write to csv
print("Writing to csv files...")
path = data_path + "pitt/"
data_df.to_csv(path + "text_pitt.csv", index=False)
print("Completed")

Writing to csv files...
Completed