## 01 - process - testset
In this notebook, we will process the original test set data, mapping file ids to text content

In [1]:
import pandas as pd

In [2]:
# please point to correct downloaded transcribed folders of the original dataset
data_path = "../../../data/" 
path = data_path + "Test Dataset/Diagnosis Testing dataset/diagnosis/test-dist/"

In [3]:
file1 = "test_results_task1.csv"

In [4]:
print("Reading testset file...")
test_df = pd.read_csv(path + file1)
print("Completed")
test_df.fillna("", inplace=True)
test_df.head()

Reading testset file...
Completed

C:\Users\Minh UBC\AppData\Local\Temp\ipykernel_29100\2520967551.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  test_df.fillna("", inplace=True)

         ID Prediction
0  adrsdt15
1  adrsdt40
2  adrsdt26
3  adrsdt67
4  adrsdt58

In [5]:
print("Rows count =", len(test_df))

Rows count = 71

In [6]:
# reading txt files
def read_txt(path, fname):
    """
        return the content of the txt file in string format
    """
    if not fname.endswith(".txt"):
        fname = fname + ".txt"
        
    try:
        with open(path + fname, encoding="utf-8") as f:
            lines = f.readlines()
            # print("Line len =", len(lines)) #, end="\r")
            text = "\n".join(lines)
            return text
    except Exception as e:
        print(f"Error reading file {path + fname}. Error = {e}")

In [7]:
txt_path = data_path + "Transcribed Data-2024-Feb-13/Diagnosis Testing Data/"
read_txt(txt_path, "adrsdt15")

"I see oh boy, almost falling on a stool trying to get in the cookie jar with his sister. Beside him looking for her as well. There's washing the dishes and spilling the water it's about in a nice window of the sink.\n"

In [8]:
# apply to dataframe to read txt content
print("Reading txt files....")
test_df["text"] = test_df["ID"].apply(lambda fname: read_txt(txt_path, fname))
print("Completed")
test_df.head()

Reading txt files....
Completed

         ID Prediction                                               text
0  adrsdt15             I see oh boy, almost falling on a stool trying...
1  adrsdt40             Well the kids are trying to get the cookies an...
2  adrsdt26             Okay, this is a family setting in a kitchen an...
3  adrsdt67             Oh, what do I see in this picture? This remind...
4  adrsdt58             While the young boy is reaching for a cookie j...

In [9]:
# write to csv file
output_path = data_path + "splits/"
test_df.to_csv(output_path + "test_text.csv",
               index=False
              )
print("Completed")

Completed

In [10]:
# reformat task1 ground truth (0: non-AD, 1: AD)
task1_gt_fname = data_path + "Ground Truth for test sets/task1.csv"
task1_df = pd.read_csv(task1_gt_fname)
task1_df.head()

         ID       Dx
0  adrsdt15  Control
1  adrsdt40  Control
2  adrsdt26  Control
3  adrsdt67  Control
4  adrsdt58  Control

In [11]:
fn = lambda label: 0 if label.lower().strip() == "control" else 1
assert fn("Control") == 0
assert fn("ProbableAD") == 1
print("Pass")

Pass

In [12]:
# apply to dataframe
task1_df["target"] = task1_df["Dx"].apply(fn)
task1_df.head()

         ID       Dx  target
0  adrsdt15  Control       0
1  adrsdt40  Control       0
2  adrsdt26  Control       0
3  adrsdt67  Control       0
4  adrsdt58  Control       0

In [13]:
# write to output csv
# output_fname = data_path + "predictions/task1_gold.csv"
output_fname = "../../evaluation/task1_gold.csv"
task1_df.to_csv(output_fname,
                index=False
               )
print("Completed")

Completed